### ISSUE TITLE
Isso tá incrivel

### ISSUE THREAD

**Issue by souzx17** [ErickLimaS/anime-website#1]
Todos os ep são de API ?

**Comment by ErickLimaS** [comment]
### Sim, todos de API. 

Eu acabei usando uma outra além da API da Anilist, que tem os episódios completos, mas em inglês.

Eu não cito ela em nenhum lugar, apenas em algumas partes dentro do site. Como acredito que essa API não tem o direito legal perante a lei para mostrar esses episódios, decidi não expor ela ou mencionar o uso (a não ser agora). 

Apenas usei para aprender mesmo, no caso, a fazer um iframe fazer streaming de alguma coisa.

Acho que os guias da comunidade do Github também não me permiti mencionar ela. Mas se você fizer uma busca por um anime no site, vai ver que tem dois formatados de resultado. Geralmente, o segundo formato é que diz de onde ela vem.
