### ISSUE TITLE
Consumet

### ISSUE THREAD

**Issue by gilbertlucas46** [ErickLimaS/anime-website#106]
Is there a required env variable to make the api works with your frontend?

I tried to deploy it to vercel like you.
https://api-consumet-org-sandy-ten.vercel.app/

but im getting errors on postman when I try to query.

![image](https://github.com/user-attachments/assets/06a9b208-2dd3-42b6-bffd-3ceab72b31cf)

PORT=Port number of the server. (optional)
BILIBILI_COOKIE=Cookie for Bilibili (optional)
PROXY=Proxies for requests (optional) (e.g. ["https://proxy1.com", "https://proxy2.com"])
REDIS_HOST=Redis host (optional)
REDIS_PORT=Redis port (optional)
REDIS_PASSWORD=Redis password (optional)
NINE_ANIME_HELPER_URL=9anime (optional)
TMDB_KEY=TMDB access token auth (optional)
RECAPTCHATOKEN=Gogoanime recaptcha token (optional)
GOGOANIME_URL=Gogoanime custom url (optional)
ZORO_URL=Zoro custom url (optional)
NODE_ENV=Environment (optional) (DEMO or PROD)

**Comment by ErickLimaS** [comment]
Zoro didnt work for me as well, so i just used the Gogoanime and Mangadex sources from Consumet on the website. 

Maybe theres a way to use Zoro, but it may take time to get things to work. For now, I'll leave as it is.

**Comment by ErickLimaS** [comment]
To close this Issue, I'd like to say this is a problem on the API. 

I can't do anything about it.

Maybe opening a issue on Consumet API Repo might help.
