### ISSUE TITLE
video not playing

### ISSUE THREAD

**Issue by skgupta507** [ErickLimaS/anime-website#46]
hello @ErickLimaS the video is not playing on my deployed site it say something about api and something went wrong iam also adding the screenshot of the issue could you help me rectify the issue.
i have hosted the api`s and added the links in the env file.
![image](https://github.com/ErickLimaS/anime-website/assets/131786207/de1cd9f3-ca07-4cf9-a145-746a2b03c7e7)
the anime loading and manga showing is working fine but playing them is not working and the episode loading time is also to much.

**Comment by ErickLimaS** [comment]
Yeah, i have seen this problem in the past 3 days. 

It seems a error with the keys extracted from the scraped source, disclosured on <a href="https://github.com/ghoshRitesh12/aniwatch-api/issues/37">this issue here</a>. 

So, sadly, we will have to wait the owner of <a href="https://github.com/ghoshRitesh12/aniwatch-api">aniwatch repo</a> try to fix it.

**Comment by skgupta507** [comment]
> Yeah, i have seen this problem in the past 3 days.
> 
> It seems a error with the keys extracted from the scraped source, disclosured on [this issue here](https://github.com/ghoshRitesh12/aniwatch-api/issues/37).
> 
> So, sadly, we will have to wait the owner of [aniwatch repo](https://github.com/ghoshRitesh12/aniwatch-api) try to fix it.

Hi @ErickLimaS thanks for the response
But that issue is also seen with the gogoanime page and vidscr page. Is there any fix for they or we have to wait it out

**Comment by ErickLimaS** [comment]
Actually, gogoanime is doing very well on my end at least. 

But Vidsrc is very bad. I personally just found few animes that could show a episode to be watched. Thats why i tagged it as "Unstable". Maybe it should be removed by now.

If Gogoanime is not working with your repo fork (i dont know it is said, english is not my first language), try checking your enviroment variables on Vercel and redeploy it. I tested the one in your .env.local and it was fine, so the env on vercel may be the problem.

**Comment by skgupta507** [comment]
hi @ErickLimaS i tried what u said deleted the deployment and added the env separately in the enviroments variable in vercel instead of the env file and vice versa .
also added the env into vercel and repo but that also didnt work what can i do to fix this can u guide me through it.
i can add u as a collaborator if u need to.

**Comment by ErickLimaS** [comment]
I saw in the env.local the url to your website. Its https://ani-project.vercel.app isnt it?

If thats the one, i gave a look on how the api calls for the gogoanime episodes on One Piece and tested with Postman. 

It returned no results using https://api-consumet-org-olive.vercel.app/anime/gogoanime/info/one-piece , but it did return something with https://api-consumet-org-olive.vercel.app/meta/anilist/watch/one-piece-episode-1 . And your Aniwatch is work as normal (just the link to episodes is not working for you, but for everyone using this api). 

So, i think the problem right now is somehow your deploy of Consumet api. 

Try redeploying it again, see if it happens on Render too. If nothing works, i think you should go to their Discord and see if someone there helps you.

**Comment by ghoshRitesh12** [comment]
Hey @ErickLimaS, I assume you are using aniwatch api, so I wanted to inform you that the episode src link endpoint has been fixed.
