### ISSUE TITLE
Multiple errors and issues

### ISSUE THREAD

**Issue by dillfrescott** [ErickLimaS/anime-website#50]
I think this is a bug. Like for example, when trying to watch an anime, the player is blank until you refresh the page, then it shows up, same with the initial gogoanime play button to load on the anime description page. Im not sure why

**Comment by ErickLimaS** [comment]
Hi. Thanks for the issue opened.

Do you remember in which anime this bug happened? Did it happened in any other? Were you logged in, using Anonymous or Google?

Sometimes it happen due to bandwith usage, but with these questions answered i can narrow down the problem.

**Comment by dillfrescott** [comment]
Hmmm it happens logged out and in, and it happened i think with aho girl, and possibly konosuba? I Cant remember I just clicked on some to test it out.

**Comment by dillfrescott** [comment]
It gets stuck forever until manual refresh...

![Screenshot_20240501_012208](https://github.com/ErickLimaS/anime-website/assets/56714680/b2e20d88-1522-4652-a737-ddede4a10076)

**Comment by dillfrescott** [comment]
Also the player gets stuck until a manual refresh nearly every time...

![aaa](https://github.com/ErickLimaS/anime-website/assets/56714680/41cbe4ee-4612-4c45-8bb6-e35f886fdca5)

**Comment by dillfrescott** [comment]
![Screenshot_20240501_012615](https://github.com/ErickLimaS/anime-website/assets/56714680/ca1cf876-f638-465a-9508-bef1b3916934)
it never loads even with a refresh. I tried the firestore database and realtime database, both with the same results. Cant comment

**Comment by ErickLimaS** [comment]
I forgot to ask you something... these bugs is happening in your forked or clone version of this repo or is on that website link on repo description?

**Comment by dillfrescott** [comment]
Oh, my fork! Sorry I forgot to mention that! I never modified the code though. I forked it to deploy it to vercel.

**Comment by ErickLimaS** [comment]
Well, it does work as usual with my deploy, even in those pages you added above.

And by seeing these screenshots, the first thing i thought was that something happened with your Firebase setup.

Have you seen some error on console or warning when hosting on LocalHost?

**Comment by ShivamB25** [comment]
@ErickLimaS anyway to contact ?

**Comment by ErickLimaS** [comment]
> @ErickLimaS anyway to contact ?

Discord: https://discordapp.com/users/513823875633643535

**Comment by ShivamB25** [comment]
> > @ErickLimaS anyway to contact ?
> 
> Discord: https://discordapp.com/users/513823875633643535

Discord server or anything or even username?

**Comment by ErickLimaS** [comment]
> > > @ErickLimaS anyway to contact ?
> > 
> > 
> > Discord: https://discordapp.com/users/513823875633643535
> 
> Discord server or anything or even username?

I dont know how to use discord, actually i just search it how to share my profile. Try looking for my username: defaultx_x
