### ISSUE TITLE
Incorrect API Key Error Despite Correct Credentials

### ISSUE THREAD

**Issue by rakeshsarkar9711** [ErickLimaS/anime-website#58]
I'm encountering an issue with my Firebase project where I'm consistently receiving an "auth/invalid-api-key" error, even though I've double-checked and confirmed that all my credentials are correct.
![Screenshot 2024-05-25 100413](https://github.com/ErickLimaS/anime-website/assets/85705268/c679963a-ad6b-4efb-89b3-c113cd51db08)

**Comment by ErickLimaS** [comment]
I just realized a didnt write on Readme about the Firebase Authentication Login Methods...

Im not sure if you've already did that, but you have to allow and accept certain sources to use the login properly, like GitHub, Default Email/Password, Google and anonymously login. Go check it on Authentication Panel -> Login Methods, on Firebase.

Tell me if it work out.

**Comment by rakeshsarkar9711** [comment]
dosen,t work
![Screenshot 2024-05-25 230103](https://github.com/ErickLimaS/anime-website/assets/85705268/ec8c6bc4-b625-4b88-8a2c-04633109fafe)
like this right?

**Comment by ErickLimaS** [comment]
I mean like this... Its in portuguese, but you get the idea
![1](https://github.com/ErickLimaS/anime-website/assets/69987890/aad27352-ff5f-4faf-809e-edd347578e90)

**Comment by rakeshsarkar9711** [comment]
![Screenshot 2024-05-25 231233](https://github.com/ErickLimaS/anime-website/assets/85705268/a783fb3b-7c20-446c-b244-d627a42ae6f3)
didn,t worked for me

**Comment by ErickLimaS** [comment]
Can you copy and put your .env.local file here?  So i can see if something is off. But BE SURE to change the data to "xxxxxx" of something like that

**Comment by rakeshsarkar9711** [comment]
NEXT_PUBLIC_CONSUMET_API_URL=https://consumet-api.herokuapp.com
NEXT_PUBLIC_ANIWATCH_API_URL=https://api-aniwatch.onrender.com
NEXT_PUBLIC_NEXT_INTERNAL_API_URL=https://lisa-eb8c3.web.app/api/animes-database
NEXT_PUBLIC_FIREBASE_API_KEY=xxxxxxxx
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=lisa-eb8c3.firebaseapp.com
NEXT_PUBLIC_FIREBASE_PROJECT_ID=lisa-eb8c3
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=lisa-eb8c3.appspot.com
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=xxxxxxxxxx
NEXT_PUBLIC_FIREBASE_APP_ID=1:6xxx3:xxxxxx
NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=xxxxxx
NEXT_PUBLIC_FIREBASE_DATABASE_URL=https://lisa-eb8c3.firebaseio.com

**Comment by rakeshsarkar9711** [comment]
![Screenshot 2024-05-26 003742](https://github.com/ErickLimaS/anime-website/assets/85705268/b20788a3-e895-4b78-959f-94216843b2fb)
now its working but its infinitly looping 


Unhandled Runtime Error
TypeError: Cannot read properties of null (reading 'filter')

Source
app\lib\fetchAnimeOptions.ts (22:50) @ filter

  20 |
  21 |         // filter to closest title name to the query 
> 22 |         filterBestResult = searchResultsForMedia.filter(item =>
     |                                                  ^
  23 |             stringToOnlyAlphabetic(item.title).toLowerCase().indexOf(regexMediaTitle) !== -1
  24 |         )
  25 |
Call Stack

and this is the error in local host

![Screenshot 2024-05-26 004302](https://github.com/ErickLimaS/anime-website/assets/85705268/fe7d6d83-c62f-4230-9a47-433fb2245cec)

**Comment by ErickLimaS** [comment]
Some errors like that used to occurre due to Api problems, but it seems ok on my side. 

On your .env.local you added the test link of Aniwatch. They have some bandwidth restrictions, so maybe thats the problem. Try to host your own on Vercel or something like that.

Tell me if it work pls :)

**Comment by rakeshsarkar9711** [comment]
vercel is not working for me same problem

**Comment by rakeshsarkar9711** [comment]
![Screenshot 2024-05-26 132006](https://github.com/ErickLimaS/anime-website/assets/85705268/a9552266-fa74-44f1-9685-48c700173260)
this error pops up when i am trying to open aniwatch ep

**Comment by ErickLimaS** [comment]
It looks like a timeout. Can you send me the aniwach url you are using?

**Comment by rakeshsarkar9711** [comment]
https://api-aniwatch.onrender.com    this one and that gogo anime is not working and search bar is not working  too

**Comment by ErickLimaS** [comment]
Thats really a Api problem, but its because youre using the demo url. You really need to host your own. You will need to follow the readme of those repos, then host them on vercel, netlify, render, etc.

**Comment by rakeshsarkar9711** [comment]
i will try and let u know

**Comment by rakeshsarkar9711** [comment]
![Screenshot 2024-05-26 225435](https://github.com/ErickLimaS/anime-website/assets/85705268/d7ebd42c-3a8d-4518-aa00-e19a4b201a97)
that go go anime is not connecting up  after hosting

**Comment by ErickLimaS** [comment]
I suggest you to make some tests on this Consumet (Gogoanime) url using Postman. 

And if its hosted on Render, it should be a timeout problem. They end the running proccess after some time, requiring to make all the build process again.
