### ISSUE TITLE
Language change

### ISSUE THREAD

**Issue by Drac1652** [ErickLimaS/anime-website#62]
Is there a way you can make the anime names display in english and not in romanji

**Comment by ErickLimaS** [comment]
I havent thought about it... But i will try to make something on the Settings Panel that the user can choose how the names will be displayed on the website.

**Comment by Drac1652** [comment]
Ok, thanks.  I hope it'll be soon

**Comment by Drac1652** [comment]
Also i have a suggestion can you link with anilist/Mal list so we can fetch
our anime data

**Comment by ErickLimaS** [comment]
Im looking on both api docs, but seems it doesnt to allow a user login from a external website, so i cant fetch any user data properly.

**Comment by Drac1652** [comment]
Ooh that's too bad.. Okay I'll keep using it there's nothin can be done

**Comment by ErickLimaS** [comment]
Actually, i just found a way to use anilist! It will take some time to make it work. I'll let you know when i commit the changes...

**Comment by Drac1652** [comment]
Awesome, thanks for the update!

**Comment by Drac1652** [comment]
Hellow,
Apart from adding anilist and language settings, can you modify the
watchlist instead of just showing watchlist anime it should be categorized
into groups like. Watching, plan to watch, completeed, on hold, and dropped.
That way can make easy to access the anime someone wants to watch and
adding animes to a specific watchlist category

**Comment by Drac1652** [comment]
Also, another thing is modifying the homepage,
How about you change the "today's recommendation" instead of selecting one
by one, you make it into a spotlight form i.e should change itself for some
seconds and i see it's in form of trending anime
(See the attachment)
Like that

**Comment by ErickLimaS** [comment]
>  modify the watchlist instead of just showing watchlist anime it should be categorized into groups like. Watching, plan to watch, completeed, on hold, and dropped. That way can make easy to access the anime someone wants to watch and adding animes to a specific watchlist category...

hey thats a good suggestion

i wasnt really inspired doing that page so i did just the necessary. I gonna give a look on it later. Theres a bunch of things on list to fix right now, so it wont be anytime soon...

**Comment by ErickLimaS** [comment]
> Also, another thing is modifying the homepage, How about you change the "today's recommendation" instead of selecting one by one, you make it into a spotlight form i.e should change itself for some seconds and i see it's in form of trending anime (See the attachment) Like that

The attch wasnt send, but i got the idea. Will add to the list as well

**Comment by Drac1652** [comment]
Ok, I'll keep using it till all fixes from the list are done

**Comment by ErickLimaS** [comment]
> Is there a way you can make the anime names display in english and not in romanji

Its done! 

i just deploy these new features on the last pull request. But you will need to logout and then login again.

**Comment by Drac1652** [comment]
Yeah, I can do that. Let me check

**Comment by Drac1652** [comment]
I've logged out and logged in and i saw the setting that allows to change
language but after allowing to change to english, nothing happens. I've
even tried to reload the page but the language stays romanji.

**Comment by Drac1652** [comment]
Hellow brother, i visited the website today and i found there are changes
in the language in some areas but the bugs (the areas where the language is
still the same)
These are
1. Homepage
2. Related animes
3. Search
4. Watch page
