### ISSUE TITLE
Displaying bugs

### ISSUE THREAD

**Issue by Drac1652** [ErickLimaS/anime-website#63]
Animes from popular animes to watch now can't be selected.
Also, Is there a way you can make the anime names display in english and not in romanji.
And thirdly can you link the website with anilist so as it can auto save data and load data

**Comment by ErickLimaS** [comment]
Im looking into the issue right now. 

And i will see if i can make some login system with anilist

**Comment by ErickLimaS** [comment]
> Animes from popular animes to watch now can't be selected.

Its fixed now!

**Comment by Drac1652** [comment]
Okay I'll be waiting for the next update

**Comment by ErickLimaS** [comment]
> And thirdly can you link the website with anilist so as it can auto save data and load data

Its done! 

You can login with your Anilist account and get the previous Favourites animes/manga to AniProject. And the progress made on AniProject wont be sent to Anilist for now, but its in the **future changes list**.

**Comment by Drac1652** [comment]
Ok, I'll do that. Thanks

**Comment by Drac1652** [comment]
Right now i may suggest to fix the language thing, so we can search anime
and view anime in English form and not japanese

**Comment by ErickLimaS** [comment]
Its finally fixed, so i'll close this issue.
