### ISSUE TITLE
[bug] movies

### ISSUE THREAD

**Issue by Drac1652** [ErickLimaS/anime-website#67]
I don't really know if it's a bug or what but in movies there's no option to play it on sub/dub.
If you play a movie it starts playing in sub directly and in video player there's no any option to change to dub version

**Comment by ErickLimaS** [comment]
yeah, i just forgot to add Dub Options to movies lol

I'll fix it when im done with the Anilist Login.

**Comment by Drac1652** [comment]
You're the best bro ✊️
I enjoy the website a lot though it has small bugs

**Comment by ErickLimaS** [comment]
You posting these Issues is really helping things get done, i really appreciate that

**Comment by Drac1652** [comment]
You're welcome, and i sent you emails about the episodes issues can't play
next episode in dub when using aniwatch server and shows an error when
using gogoanime. I hope you've seen them

**Comment by ErickLimaS** [comment]
ok, i just fixed this bug on the latest pull request, so i will close this issue for now

**Comment by Drac1652** [comment]
Awesome, thanks for the update!
