### ISSUE TITLE
Gogoanime next episode

### ISSUE THREAD

**Issue by Drac1652** [ErickLimaS/anime-website#69]
When an episode ends, and the next episode button appear, it doesn't go to the next episode instead it shows error. (This bug can be seen when only watching episodes in dub)
I've attached images to see
![20240602_181654](https://github.com/ErickLimaS/anime-website/assets/137118771/bc00e152-a8ed-44d6-8bd5-7964b1ac7dc3)

**Comment by ErickLimaS** [comment]
It seems the dub option is pretty broken, i'll add it to the Fix list. When im done i'll tell you.

**Comment by Drac1652** [comment]
Ok, let me know.

**Comment by ErickLimaS** [comment]
Its fixed now, so i'll close this issue.
