### ISSUE TITLE
[bug] Language

### ISSUE THREAD

**Issue by Drac1652** [ErickLimaS/anime-website#75]
After changing the language and logged in still the language on the website remains unchanged even after multiple reloads. The English language takes effect only on similar animes you may like (after you select one anime to watch) but all areas it's still romanji even on search.
And also the animes on most popular cannot be still selected I've tried multiple times but i can't select them.
And also keep watching now cannot be deleted, the episodes still remain there even after delete.
![IMG-20240605-WA0001](https://github.com/ErickLimaS/anime-website/assets/137118771/6ea3166c-1763-44a2-8a85-21543667a49e)

**Comment by ErickLimaS** [comment]
All issues fixed now, so i'll close this issue.

**Comment by Drac1652** [comment]
U have done a great job brother, so the next update in your list is going
to be what?
