### ISSUE TITLE
Aniwatch server is down

### ISSUE THREAD

**Issue by Drac1652** [ErickLimaS/anime-website#83]
Aniwatch server isn't responding. If you play a video it shows error and asks to reload

**Comment by ErickLimaS** [comment]
yeah, its a problem on the [Aniwatch API project](https://github.com/ghoshRitesh12/aniwatch-api) side

need to wait and see what happen now

**Comment by Drac1652** [comment]
> yeah, its a problem on the [Aniwatch API project](https://github.com/ghoshRitesh12/aniwatch-api) side
> 
> need to wait and see what happen now

Ooh that's a bummer, let's just wait

**Comment by Drac1652** [comment]
And also fix the watched mark after episode finishes it doesn't mark as watched once an episode is done, i had to do it manually

**Comment by ErickLimaS** [comment]
> And also fix the watched mark after episode...

ok, will see it later

**Comment by ErickLimaS** [comment]
Actually it was my fault... havent sync the fork i did in some time with latest commits

Its fixed!
