### ISSUE TITLE
Add to my list problem

### ISSUE THREAD

**Issue by Drac1652** [ErickLimaS/anime-website#85]
The add to my list has some issues, it delays when you add a new anime on it.
Another thing there's no my list option when you open profile it only shows, favorites, latest episodes, settings and log out, there's no my list option where i can view the planned episodes, watching or completed. That's data fetched from Anilist.
And those automatically set as complete or watching should automatically mark all the episodes as watched.

**Comment by ErickLimaS** [comment]
- The delay is the request loading, i could change something but theres no point doing it now with others things to fix.

- My list page is now added.

> And those automatically set as complete or watching should automatically mark all the episodes as watched
- Good suggestion. Will do.
