### ISSUE TITLE
Auto mark watched episodes

### ISSUE THREAD

**Issue by Drac1652** [ErickLimaS/anime-website#91]
It's a job well done for creating my list and fetching data from anilist that's a huge step bro congrats.
This suggested feature i somehow saw it in other websites. When you fetch data from anilist. All fetched episodes if are watched/marked as completed also appear marked as watched on the website. Can you fix that feature so for all fetched episodes to appear marked if the episode is already viewed.

**Comment by ErickLimaS** [comment]
Im working on it. 

Now I have added a feature to sync with Anilist. When an episode is completed, it updates the watched episodes there.

When its done, i make the PR.

**Comment by ErickLimaS** [comment]
No, i havent changed the production one. Im the only one who can see the changes for now

>  reloaded many times for it to just open the homepage

this is because of vercel free tier limit. it will be like this forever, since i dont pay a penny.

**Comment by Drac1652** [comment]
> No, i havent changed the production one. Im the only one who can see the changes for now


So when will the autosync be ready for everyone?

**Comment by ErickLimaS** [comment]
>So when will the autosync be ready for  everyone?

Its out now! It auto marks the episodes watched from Anilist, and when you watch one, it updates your anilist account with the new info.

And now i'll be closing this issue as completed.
