### ISSUE TITLE
Episodes don't play

### ISSUE THREAD

**Issue by Drac1652** [ErickLimaS/anime-website#92]
None of the episodes i try to watch plays. It just shows the same error. Both sub and dub
![20240612_211608](https://github.com/ErickLimaS/anime-website/assets/137118771/189c3933-764e-40c2-a59a-3db9aa63debf)

**Comment by Drac1652** [comment]
> can you send me the episode link?

Sorry for the trouble, i think the problem is not episode can't play but the installed PWA. I tried to play an episode direct on browser and it played but on a PWA app still doesn't play and shows API errors

**Comment by Drac1652** [comment]
https://aniproject-dev.vercel.app/watch/153288?source=gogoanime&episode=9&q=kaijuu-8-gou-episode-9&t=0

https://aniproject-dev.vercel.app/watch/21507?source=gogoanime&episode=1&q=mob-psycho-100-dub-episode-1&dub=true

Those are episodes i tried to play recently and they both give the same error and that only occur on PWA app

**Comment by ErickLimaS** [comment]
I really couldnt reproduce the error. Everything works fine here. Have you tried erasing the cookies or log out?

**Comment by Drac1652** [comment]
> I really couldnt reproduce the error. Everything works fine here. Have you tried erasing the cookies or log out?

Now it's working. I think it was because you were adding new features.
And i see you have fixed the notifications.. That's a great job bro..
So what's next for the updates?
