### ISSUE TITLE
Auto mark bug

### ISSUE THREAD

**Issue by Drac1652** [ErickLimaS/anime-website#94]
Good thing the auto mark works but sadly it marks even the episodes i haven't seen yet. It just mark all the episodes which are there.

**Comment by ErickLimaS** [comment]
Yeah, it saves anything before the episode marked. Eg: you marked episode 7 as watched, then episodes from to 1 to 6 will be marked.

**Comment by Drac1652** [comment]
> Yeah, it saves anything before the episode marked. Eg: you marked episode 7 as watched, then episodes from to 1 to 6 will be marked.

That's nice but what i mean is i have watched naruto on my anilist and i ended episode 35 but it is marked the whole season as watched and am just at 35

**Comment by ErickLimaS** [comment]
> That's nice but what i mean is i have watched naruto on my anilist and i ended episode 35 but it is marked the whole season as watched and am just at 35

I noticied this just now. Sorry. 

Some bugs just happens when its on production.... 😐

i gonna fix it now.

**Comment by Drac1652** [comment]
> > That's nice but what i mean is i have watched naruto on my anilist and i ended episode 35 but it is marked the whole season as watched and am just at 35
> 
> I noticied this just now. Sorry.
> 
> Some bugs just happens when its on production.... 😐
> 
> i gonna fix it now.

Okaay no worries brother, may i know what's on your fix list next, coz i have few suggestions i wanna put on the issue list

**Comment by ErickLimaS** [comment]
Next will be the loading between pages. It just stop working after i added the anilist login.

**Comment by ErickLimaS** [comment]
> i gonna fix it now.

See if its fixed now.

**Comment by Drac1652** [comment]
> > i gonna fix it now.
> 
> See if its fixed now.

It's fixed thanks
